export const ADD_USER = "ADD_USER";

export const SHOW_POSTS_SUCCESS = "SHOW_POSTS_SUCCESS";
export const SHOW_POST_BY_ID_SUCCESS = "SHOW_POST_BY_ID_SUCCESS";
export const SHOW_POSTS_BY_ID = "SHOW_POSTS_BY_ID";

export const LOAD_AUTHORS = "LOAD_AUTHORS";

export const SHOW_PROGRESS = "SHOW_PROGRESS";
export const SHOW_ERROR = "SHOW_ERROR";
